import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fnet Enterprise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="foricon.jpg" />
      </Head>
    </div>
    
  )
}
